// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kteajlsbkadckviiflqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZWFqbHNia2FkY2t2aWlmbHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjEyNDYsImV4cCI6MjA3MzQ5NzI0Nn0.QEl57pKOocRDKxooF4poQlN9K6CbiX60laGil42bITo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});